version: "3.8"


services:

 mongo:
  image: mongo
  ports:
   - "27017:27017"
  environment:
   - MONGODB_ROOT_USER=username
   - MONGODB_ROOT_PASSWORD=password
  volumes:
   - ./mongo:/data/db
  networks:
   - docker-net
  entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]


 mongo-express:
  image: mongo-express
  restart: always
  ports:
   - "8081:8081"
  depends_on:
   - mongo
  networks:
   - docker-net

 redis:
  image: 'bitnami/redis:latest'
  environment:
   - REDIS_PASSWORD=MyRedisPassword
  ports:
   - '6379:6379'

 kafka:
  image: durutheguru/wurstmeister-kafka:latest
  platform: linux/arm64/v8
  depends_on:
   - zookeeper
  ports:
   - "9092:9092"
  environment:
   KAFKA_ADVERTISED_HOST_NAME: localhost
   KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  networks:
   - docker-net

 zookeeper:
  image: wurstmeister/zookeeper
  ports:
   - "2181:2181"
  networks:
   - docker-net



networks:
 docker-net:

